resolver: lts-13.27
packages:
- .
flags:
  vulkan-api:
    useNativeFFI-1-0: true
    useNativeFFI-1-1: false
    useUnsafeFFIDefault: true
extra-deps:
- sdl2-2.5.0.0@sha256:9b5b19ca4caf80cbd79e5815ffea13cfa2d2215d1b2ab10dc904bbe42ca47dc2
- vulkan-api-1.3.0.0@sha256:9f905a1656c35cf15786a1f2669ab83b8f4633ca35b2affcbb05012958ab12ce
extra-include-dirs:
- extras/vulkansdk-macos-1.1.108.0/macOS/include
extra-lib-dirs:
- extras/vulkansdk-macos-1.1.108.0/macOS/lib
